apiVersion: v1
kind: PersistentVolume
metadata:
  name: free5gc-pv-mongo
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/sarang/free5gc-storage/mongo
